### PR TITLE
Add GreenShah Theme

### PR DESCRIPTION
**Pull request by yazdipour**
Dark-Green Theme

### CODE REVIEW

**Comment by justcla** [comment]
Thanks for this new theme. I'll add it into the pack.

**Comment by levigeers** [comment]
What is the image you choose as background? I am referring to the screenshot on the visualstudio store page. Really liked that one!

**Comment by yazdipour** [comment]
@levigeers I don't have the image right now, but you can set background with [ClaudiaIDE](https://marketplace.visualstudio.com/items?itemName=kbuchi.ClaudiaIDE) extension

**Comment by levigeers** [comment]
@yazdipour yup I already have Claudia for a while, but I really liked that picture you had. Do you know what "type" of picture that was? Like what catagory? Then I can google something like that. Thanks for replying that fast by the way!!

**Comment by yazdipour** [comment]
@levigeers I did an image search with my old screenshot and I found that [this website](https://www.sope.gr/home) is using it

**Pull request merged**
