### PR TITLE
Added support for VS 2019

### LINKED ISSUE #50: Add support for VS 2019
It's super easy and quick to do. See how here https://madskristensen.net/blog/how-to-upgrade-extensions-to-support-visual-studio-2019/

### PR DESCRIPTION
**Pull request by madskristensen**
Fixes #50

### CODE REVIEW

**Comment by madskristensen** [comment]
@artl93 It's considered bad practice to leave the version range on `<InstallationTarget>` open ended, since there is no way of knowing if the extension will support vNext (API deprecation, new rules enforced etc.). It could end in a crash of VS.

**Comment by artl93** [comment]
No problem. I was aware. With the modern versioning scheme, the risk of incompatibility is lower than it has been in the past - so just throwing it out there. 👍

**Comment by justcla** [comment]
Thanks for the Pull Request Mads. I appreciate it.

However, I'm inclined to reject this PR as it does not seem to provide additional support, and instead creates a maintenance issue for the future.
I'm open to including it if there is real value in locking it down to Dev16. But we both know the pain of doing otherwise unnecessary changes. I'd rather address issues as required if and when things break.

I believe this extension should already be fully compatible with VS2019.

**Comment by TuSKan** [comment]
This is the error on VS2019: The prerequisite version specified does not match the version installed
```
16-12-2018 11:08:42 AM - Microsoft VSIX Installer
16-12-2018 11:08:42 AM - -------------------------------------------
16-12-2018 11:08:42 AM - vsixinstaller.exe version:
16-12-2018 11:08:42 AM - 16.0.85
16-12-2018 11:08:42 AM - -------------------------------------------
16-12-2018 11:08:42 AM - Command line parameters:
16-12-2018 11:08:42 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2019\Common7\IDE\devenv.exe,/skuName:Community,/skuVersion:16.0.28408.50,/appidname:Microsoft Visual Studio Community 2019,/culture:en-US,/noep,C:\Users\rener\AppData\Local\Temp\VSIXogpimiov.vsix
16-12-2018 11:08:42 AM - -------------------------------------------
16-12-2018 11:08:42 AM - Microsoft VSIX Installer
16-12-2018 11:08:42 AM - -------------------------------------------
16-12-2018 11:08:42 AM - Initializing Install...
16-12-2018 11:08:42 AM - Extension Details...
16-12-2018 11:08:42 AM - 	Identifier         : VSColorThemes.8643b166-c815-4f07-b9ec-64be1f7b8a59
16-12-2018 11:08:42 AM - 	Name               : Color Themes for Visual Studio
16-12-2018 11:08:42 AM - 	Author             : Open Source Community
16-12-2018 11:08:42 AM - 	Version            : 1.0.9
16-12-2018 11:08:42 AM - 	Description        : Provides additional color themes for Visual Studio IDE. Includes themes contributed by community members plus themes from Microsoft's Color Themes Editor.
16-12-2018 11:08:42 AM - 	Locale             : en-US
16-12-2018 11:08:42 AM - 	MoreInfoURL        : https://github.com/Microsoft/VS-ColorThemes
16-12-2018 11:08:42 AM - 	InstalledByMSI     : False
16-12-2018 11:08:42 AM - 	SupportedFrameworkVersionRange : [4.5,)
16-12-2018 11:08:42 AM - 
16-12-2018 11:08:42 AM - 	SignatureState     : Unsigned
16-12-2018 11:08:42 AM - 	Supported Products : 
16-12-2018 11:08:42 AM - 		Microsoft.VisualStudio.IntegratedShell
16-12-2018 11:08:42 AM - 			Version : [12.0,)
16-12-2018 11:08:42 AM - 
16-12-2018 11:08:42 AM - 	References         : 
16-12-2018 11:08:42 AM - 	Prerequisites      : 
16-12-2018 11:08:42 AM - 		-------------------------------------------------------
16-12-2018 11:08:42 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
16-12-2018 11:08:42 AM - 		Name         : Visual Studio core editor
16-12-2018 11:08:42 AM - 		Version      : [15.0,16.0)
16-12-2018 11:08:42 AM - 
16-12-2018 11:08:42 AM - Signature Details...
16-12-2018 11:08:42 AM - 	Extension is not signed.
16-12-2018 11:08:42 AM - 
16-12-2018 11:08:43 AM - Capping recursion at 5 directories in each extension root due to 'default limit'.
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\EXTENSIONS\zmvnuj3n.cyw\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\EXTENSIONS\wsip5iun.qnf\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\EXTENSIONS\TestPlatform\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\EXTENSIONS\owgnfis0.3xs\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\EXTENSIONS\Microsoft\Web Tools\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\EXTENSIONS\Microsoft\Web Tools\Shared\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\EXTENSIONS\Microsoft\Visual Studio MPF\14.0\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\EXTENSIONS\Microsoft\Visual Studio MPF\12.0\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\EXTENSIONS\Microsoft\Visual Studio MPF\11.0\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\EXTENSIONS\Microsoft\Visual Studio MPF\10.0\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\EXTENSIONS\Microsoft\VC\ClassWizard\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\EXTENSIONS\Microsoft\Unit Test Explorer\TestWIExtension\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\EXTENSIONS\Microsoft\Portable Library Tools\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\EXTENSIONS\Microsoft\LiveShare\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\EXTENSIONS\Microsoft\Graphics\Debugger\Extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\EXTENSIONS\Microsoft\CodeSense\Framework\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\EXTENSIONS\GitHub\GitHub\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\EXTENSIONS\fmn2j1jn.ely\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Capping recursion at 5 directories in each extension root due to 'default limit'.
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Platform\Visual Studio MPF\16.0\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Platform\TreeNavigation\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Platform\TreeNavigation\GraphProvider\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Platform\Shell\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Platform\PerfMarkers\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Platform\ParallelDebugger\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Platform\NavigateTo\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Platform\NavigateTo\FileProvider\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Platform\Instrumentation\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Platform\DiagnosticsHub\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Platform\Debugger\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Platform\CPUSampling\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Web\Exports\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Web\ASPX\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\VisualStudio\Editors\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\VC\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\VC\Project\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\VC\NavigateTo\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\VC\Editor\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\VC\Debugger\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\TypeScript\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\TextMate\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\TestWindow\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\TemplateProviders\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\TeamFoundation\Team Explorer\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Search\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ReferenceManager\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ProjectServices\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Project\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ProductUpdate\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Performance Tools\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\OpenFolder\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ManagedLanguages\VBCSharp\LanguageServices\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ManagedLanguages\VBCSharp\InteractiveComponents\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ManagedLanguages\VBCSharp\ExpressionEvaluators\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Linux\Linux\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\LanguageServer\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Language\GenerateType\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Language\CallHierarchy\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\InteractiveWindow\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ExtensionManager\ServiceModule\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ErrorList\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Editor\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Diff\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\CodingConventions\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\CodeAnalysis\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\CMake\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\CMake\TestExplorer\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\CMake\Linux\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ClientDiagnostics\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ClientDiagnostics\AppResponsiveness\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Architecture Tools\Providers\Solution\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Architecture Tools\Providers\NativeCode\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Architecture Tools\Providers\ManagedProvider\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Architecture Tools\GraphProviderPackage\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMON7\IDE\COMMONEXTENSIONS\DataDesign\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Capping recursion at 5 directories in each extension root due to 'default limit'.
16-12-2018 11:08:43 AM - Found 'C:\USERS\RENER\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_B5121358\EXTENSIONS\z4swckdh.u1n\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\USERS\RENER\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_B5121358\EXTENSIONS\xorcbjdb.ntd\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\10\Desktop SDK\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\10\SDK ARM Additions\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\10\Windows Store SDK\extension.vsixmanifest'
16-12-2018 11:08:43 AM - Skipping 'C:\Users\rener\AppData\Local\Microsoft SDKs' as it doesn't exist
16-12-2018 11:08:43 AM - The extension with ID 'VSColorThemes.8643b166-c815-4f07-b9ec-64be1f7b8a59' is not installed to Microsoft Visual Studio Community 2019.
16-12-2018 11:08:46 AM - Extension cannot be installed to the following products due to missing prerequisites:
16-12-2018 11:08:46 AM - 	Microsoft Visual Studio Community 2019
16-12-2018 11:08:46 AM - 		-------------------------------------------------------
16-12-2018 11:08:46 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
16-12-2018 11:08:46 AM - 		Name         : Visual Studio core editor
16-12-2018 11:08:46 AM - 		Version      : [15.0,16.0)
16-12-2018 11:08:46 AM - 		Error        : The prerequisite version specified does not match the version installed
16-12-2018 11:08:46 AM - 
16-12-2018 11:08:46 AM - System.InvalidOperationException: No modifications could be applied.
   at VSIXInstaller.MultipleChangePage..ctor(ExtensionData data)
   at VSIXInstaller.LoadingPage.<>c__DisplayClass15_1.<OnLoaded>b__2()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

```

**Comment by artl93** [comment]
@Jeff Kelly<mailto:jekelly@microsoft.com> / @Andrew Sarratori<mailto:ansarrat@microsoft.com> – is this a known thing?

**Comment by artl93** [comment]
This is the open source one that Justin created that's just the themes right?

From: Art Leonard <artl@microsoft.com>
Sent: Monday, December 17, 2018 9:20 AM
To: Microsoft/VS-ColorThemes <reply@reply.github.com>; Microsoft/VS-ColorThemes <VS-ColorThemes@noreply.github.com>; Jeff Kelly <jekelly@microsoft.com>; Andrew Sarratori <ansarrat@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Microsoft/VS-ColorThemes] Added support for VS 2019 (#51)

@Jeff Kelly<mailto:jekelly@microsoft.com> / @Andrew Sarratori<mailto:ansarrat@microsoft.com> - is this a known thing?

**Comment by benhysell** [comment]
@prnadago has this been published yet?  Just went to https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.ColorThemesforVisualStudio and it does not list VS2019 as a 'Works With' target.

I pulled down the latest from the marketplace and could not install against VS2019

**Comment by prnadago** [comment]
Hey @benhysell not yet. I'm not the one who publishes it, but I'll follow up internally to find out the delay and get back with an eta. Thanks!

**Pull request merged**
