### PR TITLE
OneDarkVariant theme with requested changes

### PR DESCRIPTION
**Pull request by aaron-bond**
Hi,

I've taken the OneDarkVariant created by @DividedByCero in https://github.com/microsoft/VS-ColorThemes/pull/60 and made the requested changes. All credit goes to original author here, I just really like this theme so wanted to make sure it makes it into master.

Thanks!

### CODE REVIEW

**Comment by DividedByCero** [comment]
@aaron-bond Thanks for helping me out with this. I had some troubles removing the CT_INVALID entries and passing the file through the extension i found in the marketplace to editing this kind of color scheme.

It seems like the editor always restore those entries in the file and i didn't find a way to solve it. I would like to know if you took the file and just remove the entries including the categories using just a text editor or if you use the current extension available in the process.

**Comment by aaron-bond** [comment]
Yeah I just manually removed the entries. It was a bit tedious but the theme is too good to not have it in :)

**Comment by DividedByCero** [comment]
> Yeah I just manually removed the entries. It was a bit tedious but the theme is too good to not have it in :)

I guess i would need to do the same if i want to add some changes. Thanks.

**Comment by aaron-bond** [comment]
> 
> 
> > Yeah I just manually removed the entries. It was a bit tedious but the theme is too good to not have it in :)
> 
> I guess i would need to do the same if i want to add some changes. Thanks.

No problem at all. Thanks for porting the theme, it's working great.

**Comment by Newrad0603** [comment]
@aaron-bond Can you include the theme screenshot here as well? @DividedByCero Since this will be going in, mind if I drop the old PR?

**Comment by aaron-bond** [comment]
Here's the screenshot of the theme:

Capture

**Pull request merged**
