### PR TITLE
Add Sublime Material Dark theme

### PR DESCRIPTION
**Pull request by revosw**
The file has an extension of .vstheme, however all others are xml... Should I change that?

### CODE REVIEW

**Comment by Newrad0603** [comment]
The project requires xml files so it can convert them to pkgdef files to bundle with the extension, so you;ll need to change the extension. You'll also need to update the vsixmanifest to include the pkgdef, so the extension can find your theme at runtime.

**Comment by justcla** [comment]
There's no need to update the VSIX manifest. Instead, you add an entry to the [ThemeRegistration](https://github.com/Microsoft/VS-ColorThemes/blob/master/VSColorThemes/ThemeRegistration.pkgdef) pkgdef file.

**Comment by justcla** [comment]
I will update the pgkdef entries as required.

**Comment by justcla** [comment]
The Sublime Material Dark theme looks a lot like the Dark theme. Can you tell us how it differs? Better still, can you provide a screenshot of what it looks like that highlights the main differences?
Thanks.

**Comment by revosw** [comment]
There is really not much that differs - many of the shades of gray have been made uniform, so that there are next to no visible borders. I am still a bit uneasy about the breakpoint bar, as it's not intuitive that the bar actually exists when it has the same color as the text editor, however the minimalistic / uniform style didn't quite punch through with a breakpoint bar that had a gray color that differed from the text editor. The border separating the project/solution menu from the text editor has gotten a transparent blue color, having only VerticalResizeGripMiddle defined, and not Top nor Bottom.

Really - I wouldn't mind it being set off for a while until I have progressed further with a design that feels more unique, to be honest I just copied the Dark theme and made adjustments to highlighting colors and the gray colors everywhere to make it almost borderless.

**Comment by justcla** [comment]
Cool. Thanks for the description.

> Really - I wouldn't mind it being set off for a while

Well, it's live now! :-D
Feel free to submit improvements to it as you develop them.
Note, you might want to rebase to the latest master. I renamed the file (from vstheme to XML) and I included references to it in a couple of places.

**Comment by revosw** [comment]
Cool, man :')
Gotta try making more out of this theme

**Pull request merged**
