### PR TITLE
A complete overhaul of Sublime Material (Dark)

### PR DESCRIPTION
**Pull request by revosw**
- I renamed the theme to Material Dark
- Many UI elements and text editor colors now actually use colors from the Material palette as of [Google's own specifications](https://material.io/design/color/the-color-system.html#color-usage-palettes)
- Doesn't look horrible like the last version

### CODE REVIEW

**Comment by justcla** [comment]
Thanks for the contribution. Can you paste a screenshot of what the new theme looks like?
Better still if you can also post a similar screenshot of the old version to make it easier to tell the difference.

**Comment by revosw** [comment]
New style


Old style

**Comment by revosw** [comment]
Some of the new changes:
- Line highlighter and matching words

- C++ import and class

- HTML, XML and XAML

- LESS, SASS and CSS


And more.

**Comment by justcla** [comment]
Thanks

**Comment by revosw** [comment]
I come across more and more that needs a little changin' ... Hold on let me upload these fixes too

Old visual studio installer interface


New visual studio installer interface

**Comment by revosw** [comment]
Ready again, can merge anytime

**Comment by justcla** [comment]
Looks good. Is it OK for me to squash the commits?

**Comment by revosw** [comment]
Yep, that's all fine

**Pull request merged**
