### PR TITLE
Updated syntax highlighting colors

### PR DESCRIPTION
**Pull request by revosw**

### CODE REVIEW

**Comment by justcla** [comment]
What changes did you make here?

**Comment by revosw** [comment]
Wait, it doesn't even look like the changes I made to verbatim strings even had any effect... Going to try once more to update the xml file

**Comment by revosw** [comment]
And now suddenly all my changes are no longer there? I'll post another update after I've changed all the colors back to what I intended... No idea what happened, maybe I copied and deleted the wrong one by accident

**Comment by revosw** [comment]
Wow this is very strange, if I export the file and don't change the extension from .vstheme to .xml after export, it preserves all my changes. The moment I change the extension to .xml, it automatically goes back to all default values. I don't know what black magic is happening, but I'll upload the file with .vstheme extension and try to change the name afterwards

**Comment by revosw** [comment]
Changes to Text Editor:

C++ parameters (FF7F7F7F -> FFC8C8C8)

C++ variables (FFFFFF -> FFC8C8C8)

C++ macros (FFBD63C5 -> FFBD63C5)

User types, C++ user types, C++ class templates (FF4EC9B0 -> FFF07178)

Various comments (FF008000 -> FF546E7A)

Literal, text, C++ user defined literals, C++ fields (FFDADADA -> FFC8C8C8)

**Comment by revosw** [comment]
Various strings (FFD69D85 -> FFC3E88D)

**Comment by revosw** [comment]
Ok I think this is good, you can merge the changes

**Comment by justcla** [comment]
Looks good. Thanks for the updates. Merged.

I'll package and release a new version to the Marketplace soon.

**Comment by justcla** [comment]
Looks good. Thanks for the updates. Merged.

I'll package and release a new version to the Marketplace soon.

**Pull request merged**
